// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKhP3xt6uTJ6Csoh7C3WzAdVgFP1pe-R0',
    appId: '1:172775608092:web:2000120f99548dd73bb4d9',
    messagingSenderId: '172775608092',
    projectId: 'focusblock-d7179',
    authDomain: 'focusblock-d7179.firebaseapp.com',
    storageBucket: 'focusblock-d7179.firebasestorage.app',
    measurementId: 'G-1XFKXB5Z02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBd3uNOQEmIM8TYJz-Z41Q3RojB5Z7vfk',
    appId: '1:172775608092:android:f4d206efe04e7bbf3bb4d9',
    messagingSenderId: '172775608092',
    projectId: 'focusblock-d7179',
    storageBucket: 'focusblock-d7179.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnfY0xuyZIOcnr6rZlGBCGZWLq7gcYGEQ',
    appId: '1:172775608092:ios:14eaffc1a5f9c8bb3bb4d9',
    messagingSenderId: '172775608092',
    projectId: 'focusblock-d7179',
    storageBucket: 'focusblock-d7179.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnfY0xuyZIOcnr6rZlGBCGZWLq7gcYGEQ',
    appId: '1:172775608092:ios:14eaffc1a5f9c8bb3bb4d9',
    messagingSenderId: '172775608092',
    projectId: 'focusblock-d7179',
    storageBucket: 'focusblock-d7179.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKhP3xt6uTJ6Csoh7C3WzAdVgFP1pe-R0',
    appId: '1:172775608092:web:fecbdb634d0e79d33bb4d9',
    messagingSenderId: '172775608092',
    projectId: 'focusblock-d7179',
    authDomain: 'focusblock-d7179.firebaseapp.com',
    storageBucket: 'focusblock-d7179.firebasestorage.app',
    measurementId: 'G-RXWXPF3J44',
  );
}
